### ISSUE TITLE
CSS library research

### ISSUE THREAD

**Issue by KEDuran** [Holiday-Secret-Santa/Secret-Santa-App#43]
- [x] review CSS library styles and documentation
- [x] report to team which CSS library looks ideal

**Comment by KEDuran** [comment]
# Research Results on CSS Libraries
Here are note for the CSS libraries covered in the [React Libraries in 2020 article](https://www.robinwieruch.de/react-libraries#react-ui-libraries) source article. 

## Ant Design - [click here to access library](https://ant.design/)
Overall, there are a lot of design capabilities available in this library. For example, the components are come pre-developed and we would only have to insert the actual component (pre-designed by Ant) into our code. I included an example of sandbox sample code that we would use for inserting a `DatePicker` component from Ant. 

![image](https://user-images.githubusercontent.com/58799056/92819449-6eeaab00-f38e-11ea-8a8d-79cc91e33276.png)

## Chakra UI - [click here to access library](https://chakra-ui.com/)
Overall, Chakra has a similar feel to Bootstrap when it comes to how they design components. We would actually need to create component without our project files (i.e. components do not come pre-developed like in Ant). Here is a screenshot of code we would use to create a button. 

![image](https://user-images.githubusercontent.com/58799056/92819828-d7d22300-f38e-11ea-9d9a-51c54987e16d.png)

## Tailwind UI - [click here to access library](https://tailwindui.com/preview)
As @JDMartinez1531 mentioned earlier, this CSS library is still in the preview stage. Only certain components are available to the public, so it appears that we may not have access to all components at this time. I also think we **_should not_** use this library. 

## Semantic UI - [click here to access library](https://react.semantic-ui.com/elements/button/#types-button)
Overall, the documentation for this library is pretty good. The code used for component development looks a little different, but not too difficult. Here is an example of the code we would use to insert a button. 

![image](https://user-images.githubusercontent.com/58799056/92821001-377cfe00-f390-11ea-94bc-16dccfd7bd21.png)

## Material UI
No review - previously used this library in other projects.

## React Bootstrap
No review - previously used this library in other projects.

**Comment by JDMartinez1531** [comment]
Not sure if this is still true, but I had heard that Ant requires you to install their entire library, while other frameworks allow you to just install what you need. So I would be wary of this.

I like what I see with semantic, but I am worried we will run into a problem there won't be any documentation for as the community is much smaller.

Chakra looks really nice, but I was reading that styling can be difficult. I'm up for it, however it seems like there are even some components are supposedly impossible to style.
Check [here](https://whoisryosuke.com/blog/2020/limitations-of-chakra-ui/)

**Comment by KEDuran** [comment]
I added some notes for Material UI just in case we want to use this one.

**Comment by KEDuran** [comment]
On 9/10, the team met to discuss which CSS library we will use. The team agreed to test Chakra UI with the Google React Apps homework assignment to test the functionality of this new UI.

I am closing this issue since preliminary research is complete. Thanks!
